name: appmonitor
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_database: ^11.3.5
  fl_chart: ^1.0.0
  firebase_core: ^3.13.0
  flutter_local_notifications: ^19.2.1
  intl: ^0.19.0
  google_fonts: ^6.2.1
  lottie: ^2.2.0 # Added for Lottie animation

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/intro.json
    - assets/water.json
